### ISSUE TITLE
Plán implementácie

### ISSUE THREAD

**Issue by MartinR255** [TIS2022-FMFI/optimal-dispatcher#15]

**Comment by Beka14** [comment]
[Návrh systému.docx](https://github.com/TIS2022-FMFI/optimal-dispatcher/files/10315107/Navrh.systemu.docx)

**Comment by Beka14** [comment]
Updated verzia:

[Návrh systému.docx](https://github.com/TIS2022-FMFI/optimal-dispatcher/files/10327190/Navrh.systemu.docx)

**Comment by Beka14** [comment]
[Návrh systému.docx](https://github.com/TIS2022-FMFI/optimal-dispatcher/files/10527980/Navrh.systemu.docx)
