### ISSUE TITLE
Vytvorenie návrhu UI

### ISSUE THREAD

**Issue by MartinR255** [TIS2022-FMFI/optimal-dispatcher#3]

**Comment by Beka14** [comment]
[ui.zip](https://github.com/TIS2022-FMFI/optimal-dispatcher/files/9792254/ui.zip)

Prvý (veľmi naivný) návrh UI - musíte si stiahnuť : https://wireframesketcher.com/download.html a potom otvoriť zip, alebo prikladám aj obrázky



![Image](https://user-images.githubusercontent.com/99792924/195990975-32137bfb-7cdf-46e0-a953-cf9b2d7f53d1.png)



![Image](https://user-images.githubusercontent.com/99792924/195990982-2d7a155c-cd8d-4536-b86e-e0d266ce6220.png)



![Image](https://user-images.githubusercontent.com/99792924/195990984-c8f466ab-a350-495b-a2dd-e3358b76b29e.png)

**Comment by MartinR255** [comment]
Dosť sa mi páči tento návrh a moc by som nemenil na ňom. Mám len pár vecí ešte.
- musíme to prepísať do ang.
- registrácia by mohla byť skrytá na somostantnom page
- vedľa loginu by mohol byť button "Sign as guest" (toto je funkcia len na prezeranie dát)
- a teda musíme potom mať pre usera bez účtu ešte jeden page kde sa nezobrazia časti ako profil a pridať ale iba niečo ako login alebo registration 

Snáď som to príliš neprekomplikoval. Keby hej kľudne to môžem dorobiť aj ja.

**Comment by Beka14** [comment]
Super nápady, ja to spravím v pohode :) dik za feedback

**Comment by Beka14** [comment]
[ui2.zip](https://github.com/TIS2022-FMFI/optimal-dispatcher/files/9798089/ui2.zip)





![Image](https://user-images.githubusercontent.com/99792924/196120820-38ef5c26-179a-4401-b7e2-1f05507cdb4b.png)



![Image](https://user-images.githubusercontent.com/99792924/196120830-748da4f5-1d43-487e-9e28-652814537781.png)



![Image](https://user-images.githubusercontent.com/99792924/196120837-623518af-f9dd-4a80-bca9-9ba285c09ba4.png)



![Image](https://user-images.githubusercontent.com/99792924/196120849-cf6c69c8-f47c-4275-bb52-7432948c32ec.png)



![Image](https://user-images.githubusercontent.com/99792924/196120855-714e2a5e-2755-4850-85b0-9c9a1151962e.png)

**Comment by Beka14** [comment]
Spravila som taký skúšobný návrh podľa nášho stretnutia ... Určite som na niečo zabudla, takže píšte :D Nieje to ešte úplne finálne aby som to zbytočne nerobila celé ak tam budú chyby 

![Image](https://user-images.githubusercontent.com/99792924/200167682-11efb9ea-2078-4c5b-974f-00fd148cac62.png)



![Image](https://user-images.githubusercontent.com/99792924/200167688-fd320ca3-4cfa-4a50-9c18-d7428c53e41f.png)



![Image](https://user-images.githubusercontent.com/99792924/200167689-1b1d1796-0928-4c54-82fa-5e51a53fae65.png)



![Image](https://user-images.githubusercontent.com/99792924/200167693-6d8c8306-989f-415d-95a8-6eb5d507be72.png)



![Image](https://user-images.githubusercontent.com/99792924/200167698-aedcf9f5-e677-4c4d-a2a5-bac6338fd783.png)



![Image](https://user-images.githubusercontent.com/99792924/200167700-22738c20-b00c-41f7-90c6-55758424d09a.png)



![Image](https://user-images.githubusercontent.com/99792924/200167701-7aae502d-ba55-4ed6-b6b4-75a2c1eabc5e.png)



![Image](https://user-images.githubusercontent.com/99792924/200167703-935bfecc-e865-45be-b0f1-a912f8f0ce80.png)

**Comment by lubkka** [comment]
Na tej stranke kde sa maj prihlasovat sme sa tusim bavili ze by malo byt nieco ako ,,Zabudol som heslo", alebo sme to zavrhli?
Inac mi nic nenapada, vyzera to dobre

**Comment by Beka14** [comment]
Niektoré updatnuté screeny podľa toho, čo sme prediskutovali na našom stretnutí:



![Image](https://user-images.githubusercontent.com/99792924/202792676-b799c089-7214-47a5-9bd8-fcb7e226887f.png)
![Image](https://user-images.githubusercontent.com/99792924/202792677-ab3c21ba-3a54-4d89-96be-79b4c932dcb6.png)
![Image](https://user-images.githubusercontent.com/99792924/202792680-1e3c3094-ef61-4688-9d2a-bd0adf201cf9.png)
![Image](https://user-images.githubusercontent.com/99792924/202792678-c4a8dbea-a548-4ec5-b8b9-0e0ef7ca06bc.png)
![Image](https://user-images.githubusercontent.com/99792924/202792679-5a9bda19-e1ca-4211-83ec-4567813db639.png)
![Image](https://user-images.githubusercontent.com/99792924/202792682-0ac97b1f-3816-48dd-aa18-dcd7b4fd767b.png)
