### ISSUE TITLE
Vytvorenie databázového modelu

### ISSUE THREAD

**Issue by MartinR255** [TIS2022-FMFI/optimal-dispatcher#5]

**Comment by MartinR255** [comment]
Zatiaľ mám takýto model DB. Podarilo sa mi rozbiť tie prístupy do viacerých tabuliek ale budem rád za nejakú odozvu, keďže to nemusí byť úplne správne. Jeden file je PNG modelu a další môžete otvoriť a editovať v tomto super free editore https://app.diagrams.net/. Kľudne opravte čo sa Vám nezdá a nahrajte to sem.
[DB-model.zip](https://github.com/TIS2022-FMFI/optimal-dispatcher/files/9944844/DB-model.zip)

**Comment by MartinR255** [comment]
![gefco-database-model-latest](https://user-images.githubusercontent.com/79110399/200145040-5fbc9281-a3e8-4a8e-866a-e27b3a5c76f5.png)

**Comment by Beka14** [comment]
Ten read access teda nebudeme riešiť? Resp. môžu všetci všetko čitať? Taktiež možno v Transportations by som zmenila owner_id na dispatcher_id ale to je len formalitka ... inak všetko super zamňa :)

**Comment by MartinR255** [comment]
user_access záznam by bolo právo na čítanie a boolean stĺpec write_access by vravel či aj zapisovať môže
