### ISSUE TITLE
Vytvorenie UML state a UML sequence diagramu

### ISSUE THREAD

**Issue by MartinR255** [TIS2022-FMFI/optimal-dispatcher#9]

**Comment by lubkka** [comment]
![Image](https://user-images.githubusercontent.com/100282378/200640503-0faa6574-b5b8-4447-babe-3bdcefe8178c.jpg)

**Comment by lubkka** [comment]
Ahojte, tu je sequence diagram obycajneho pouzivatela, admina spravim ked budeme vediet ako s tymi grupami to budeme riesit

**Comment by lubkka** [comment]
Ahojte, posielam upraveny sequence diagram na usera a sequence na admina

[Untitled Diagram.zip](https://github.com/TIS2022-FMFI/optimal-dispatcher/files/10005040/Untitled.Diagram.zip)



![Image](https://user-images.githubusercontent.com/100282378/201714832-af381ac7-b758-4bbd-a944-8f80fdc90459.jpg)
![Image](https://user-images.githubusercontent.com/100282378/201714833-cafc7ae5-d4c6-4bfa-8521-5579aadf7f38.jpg)

**Comment by lubkka** [comment]
![Image](https://user-images.githubusercontent.com/100282378/201996514-cd8c2109-9258-44d2-96fd-fca611fe6262.jpg)
![Image](https://user-images.githubusercontent.com/100282378/201996513-4caa4213-abcd-4426-ae2a-f2cdd9df53b0.jpg)

**Comment by lubkka** [comment]
![Image](https://user-images.githubusercontent.com/100282378/203396799-b38aa44c-1de6-4c91-811b-dcd7950e86b3.png)

**Comment by lubkka** [comment]
Sekvenčný diagram prihlásenia usera

![Image](https://user-images.githubusercontent.com/100282378/213344651-5cb9fb11-0be0-4226-88c0-423d2123cf4a.png)
